services:
  - type: web
    name: superai-plus-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: 8489104550:AAFBM9lAuYjojh2DpYTOhFj5Jo-SowOJfXQ
      - key: HUGGINGFACE_TOKEN
        value: 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
